### ISSUE TITLE
FE - layout

### ISSUE THREAD

**Issue by geromyc** [ECE461-Group5/Trustworthy-Module-Registry#171]
- [ ] Adjust frontend containers for the navigation bar and permanent page features to match design.
- [ ] Container field in middle is for displaying content related to endpoints and page functionality.
- [ ] Ensure state machine lines up with API endpoints
- [ ] The enter name field for upload is no longer needed. Since it is metadata and we shouldn't alter the OpenAPI format, it is not needed.

**Comment by derekpetersen21** [comment]
I was able to change the colorway and add in Purdue logo. For some reason I could not change any of the structure of the containers without it breaking. I could not figure out why.
