### ISSUE TITLE
FE - layout reorganize

### ISSUE THREAD

**Issue by geromyc** [ECE461-Group5/Trustworthy-Module-Registry#203]
- [ ]  Adjust frontend containers for the navigation bar and permanent page features to match design.
- [ ]  Container field in middle is for displaying content related to endpoints and page functionality.
- [ ]  Ensure state machine lines up with API endpoints
- [ ] The enter name field for upload is no longer needed. Since it is metadata and we shouldn't alter the OpenAPI format, it is not needed.

**Comment by derekpetersen21** [comment]
FE layout was finalized with adding the dropdown menu to the directory page.
